// Refreshes the list of Scryfall Tagger tags the "What it does" filter can search.
// Scryfall has no API for these, so this reads the tag list page: node scripts/otags.mjs
import { writeFileSync } from 'node:fs'

const html = await (await fetch('https://scryfall.com/docs/tagger-tags', { headers: { 'User-Agent': 'ImpulseCaster/1.0', Accept: 'text/html' } })).text()
const tags = [...new Set([...html.matchAll(/oracletag%3A([a-z0-9-]+)"/g)].map((m) => m[1]))]
    // set cycles, typal tags (the creature type filter covers those) and errata notes aren't about what a card does
    .filter((t) => !/^(cycle-|type-errata-|tribal-|typal-|name-errata|\d)/.test(t))
    .sort()

writeFileSync(new URL('../app/Components/Searchbar/otags.ts', import.meta.url),
    `// Scryfall Tagger tags (otag:) about what cards do. Generated by scripts/otags.mjs; don't edit by hand.\nexport const OTAGS = ${JSON.stringify(tags.join(' '))}.split(' ')\n`)
console.log(`${tags.length} tags`)
